### PR TITLE
Adds new emoji

### PR DESCRIPTION
**Pull request by MaicolAntali**
Adds new emoji & fixes the order according to the [official unicode list](https://unicode.org/emoji/charts/emoji-list.html). 
I have also fixed some formatting issue.

⚠️ Have some breaking changes: Some names have changed to follow the official naming convention.
E.g: From: `"hugging_face": "🤗"` to `"smiling_face_with_open_hands": "🤗"`

_Note: To do this I have written a `python` script that automates all the process. (If you want I can share it)_

### CODE REVIEW

**Comment by dcdunkan** [comment]
Hi, thank you for the contribution.

While I appreciate your effort, it seems that the emoji count has went down from 3961 to 3664. And it should be 4115 with the addition of the new emoji. I investigated the issue a little bit and realised that the emoji list that you're using (the official one at unicode.org) does not list the skin tone variations, they're listed on a separate page. So, that needs to be fixed.

We've been getting the list of emoji from EmojiPedia using a [script](https://github.com/dcdunkan/emoji-scraper) for scraping Apple emoji from there. And personally I think it is easier to fetch from EmojiPedia for now.

**Comment by MaicolAntali** [comment]
Ok thanks, I close this PR. 🤗

**Comment by dcdunkan** [comment]
Oh, you didn't have to close it :) I'd appreciate if you can take the job, use the mentioned script to update the list and be a contributor. It's okay if you can't. Thank you anyway.

**Comment by MaicolAntali** [comment]
Ohh yes I can handle it but I will create a new PR. Will be more clear.

**Comment by dcdunkan** [comment]
Awesome!

**Pull request closed without merging**
