### PR TITLE
Added emoji file parsing

### LINKED ISSUE #3: Add support for new Unicode 14 emojis
This plugin MUST have new emojis coming from Unicode 14, even if they haven't been added to Telegram yet — soon they will come.

This is related to PR #2

### LINKED ISSUE #4: Add support for skin-toned emojis
This plugin MUST support [skin-toned emojis](https://unicode.org/emoji/charts/full-emoji-modifiers.html) (👍👍🏻👍🏼👍🏽👍🏾👍🏿) since they're a fundamental part of Unicode emojis.

Quick thoughts:
- Maybe it can use neutral-toned emojis (👍) + Unicode general skin tone codes (🏻🏼🏽🏾🏿) // Is this possible?
- It can be accessed like this:
```ts
ctx.emoji`${"like:medium-dark"}` // 👍🏾
ctx.emoji`${"punch:light"}` // 👊🏻
ctx.emoji`${"raised_hands"}` // 🙌
```

### PR DESCRIPTION
**Pull request by andrrms**
Added a script to parse official emojis list from txt to JSON. This still needs one last fix in src/emojis.ts typing. I'll be grateful if someone can fix this.

Fix #3 
Fix #4
References #2

### CODE REVIEW

**Comment by andrrms** [comment]
I fixed type errors. In order to do that, I needed to change emojis.json format, but changes was already reflected in another files. Upon review, if no errors are found, the plugin will be ready to enter its 1.0 version, thus being published in official documentation and in module repositories such as NPM and Deno Land.

**Comment by KnorpelSenf** [comment]
Are you aware of https://github.com/gurmanbh/emoji-scraper?

It may also make sense to simply extract the emoji that TDesktop ships. Those are already pre-formatted as JSON. Since we're building Telegram bots, all we need to support is what Telegram supports. Check out the file `Telegram/lib_ui/emoji_suggestions/emoji_autocomplete.json` in https://github.com/telegramdesktop/tdesktop. That's where I took the file from that I submitted in #2.

**Review by KnorpelSenf — APPROVED** [review]
Otherwise, if you are happy with this PR and you would like to keep on maintaining your own script, this looks good to me. The emoji names changed, so you need to adjust the example in the README, but I have tested the code in this PR and it works.

**Comment by andrrms** [comment]
At the end, the solution presented at #2 was the best. I didn't implemented it because I didn't knew where this file was obtained, but now I know and it gets easier to work with. Now with new changes implemented, I'll need again for approval.

As I said above, upon review, if no errors are found, the plugin will be ready to enter its 1.0 version, thus being published in official documentation and in module repositories such as NPM and Deno Land.

**Comment by andrrms** [comment]
`A wild PR has appeared.`

Jokes aside, I'll close this PR since a better one came out. See #6.

**Pull request closed without merging**
