### PR TITLE
Feat: Compat flavor

### LINKED ISSUE #8: Context flavour does not respect adjusted return types of `ctx.reply`
# Feature request

If I adjust the return type of `ctx.reply` using a different plugin, such as the hydrate plugin, I would like the type of `ctx.replyWithEmoji` to adjust accordingly. This makes it necessary to use a transformative context flavour, rather than an additive one.

### PR DESCRIPTION
**Pull request by KnightNiwrem**
Closes #8
Closes #9

### CODE REVIEW

**Comment by KnorpelSenf** [comment]
Related: https://github.com/grammyjs/hydrate/pull/1

**Comment by KnorpelSenf** [comment]
This supercedes #10, correct?

**Comment by andrrms** [comment]
> This supercedes #10, correct?

Looks like so.

This works fine to me! In addition to what I said [here](https://github.com/grammyjs/hydrate/pull/1#issuecomment-1097970197), if there is nothing more to do, we should merge it.

**Review by KnorpelSenf — APPROVED** [review]
LGTM!

**Pull request merged**
