### PR TITLE
(Proper) Emojis + Skin toned emojis and a script to fetch

### LINKED ISSUE #3: Add support for new Unicode 14 emojis
This plugin MUST have new emojis coming from Unicode 14, even if they haven't been added to Telegram yet — soon they will come.

This is related to PR #2

### LINKED ISSUE #4: Add support for skin-toned emojis
This plugin MUST support [skin-toned emojis](https://unicode.org/emoji/charts/full-emoji-modifiers.html) (👍👍🏻👍🏼👍🏽👍🏾👍🏿) since they're a fundamental part of Unicode emojis.

Quick thoughts:
- Maybe it can use neutral-toned emojis (👍) + Unicode general skin tone codes (🏻🏼🏽🏾🏿) // Is this possible?
- It can be accessed like this:
```ts
ctx.emoji`${"like:medium-dark"}` // 👍🏾
ctx.emoji`${"punch:light"}` // 👊🏻
ctx.emoji`${"raised_hands"}` // 🙌
```

### PR DESCRIPTION
**Pull request by dcdunkan**
[EmojiPedia](emojipedia.org) has [confirmed](https://emojipedia.org/telegram/) that Telegram uses Apple emojis. So, I tried scraping the site, and they have skin toned emojis too.
I have made a JSON and a TS file which exports emoji object as default. The TS file has has simple JSDoc comments, in the format "😀 Grinning Face" as @KnorpelSenf [suggested here](https://t.me/grammyjs/32910). I am not sure about which file to use for the plugin. It contains 3961 emojis at the moment.

I have made a script to scrape them. Also, I don't think it can be used forever. And it's scraping, it takes a lot of time. Around ~20+ minutes. And the script could be much much faster.

### CODE REVIEW

**Review by KnorpelSenf — APPROVED** [review]
This looks like a solid approach. I leave testing and implementation details to you, but I approve of this concept.

**Review by andrrms — APPROVED** [review]
I've tested and everythink works fine. As you said, it takes a lot of time (almost 1 hour on my modest computer), but since this is a one-time build per major version, I don't see any problems here.

It just needs some folder path adjustments but I can do these by myself. Nicely done script! 😁

If I may, I would even like to suggest something. Like me, other people might want a script to get up to date emojis like that, and there aren't that many currently (and I don't think any that get from Emojipedia). If you don't mind, it would be nice to store this code in a separate repository, with proper build instructions and so on. As you made the script, it's only fair that the repository is yours, but if you don't want to have this work I can do it.

I'll await for your decision on this request to merge it and if you agree with it, I'll merge only final emoji lists.

**Comment by dcdunkan** [comment]
> If you don't mind, it would be nice to store this code in a separate repository, with proper build instructions and so on.

I'll do it and update the PR.

**Comment by dcdunkan** [comment]
I am doing a final test and then I'll push the script to [dcdunkan/emoji-scraper](https://github.com/dcdunkan/emoji-scraper) (Currently empty, I'll leave a comment when it's done). I have deleted the fetching script from the PR, so I think you can merge it now.

**Comment by andrrms** [comment]
> I am doing a final test and then I'll push the script to [dcdunkan/emoji-scraper](https://github.com/dcdunkan/emoji-scraper) (Currently empty, I'll leave a comment when it's done). I have deleted the fetching script from the PR, so I think you can merge it now.

Merging rn. Just a suggestion, would be nice too if you compile scripts into an .exe file and bundles it into releases alongside code.

Closes #3, closes #4

**Comment by dcdunkan** [comment]
@AndreoliBR I have pushed the fetching script to my repo and released it.
Just leaving the link here: https://github.com/dcdunkan/emoji-scraper

**Pull request merged**
